/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipaint;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.List;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import minipaint.Shape;

/**
 *
 * @author alaae
 */
public class Draw extends javax.swing.JFrame {

    /**
     * Creates new form Draw
     */
    private DrawCanvas drawPanel;
    Drawing draw = new Drawing();
    ArrayList<String> names = new ArrayList<>();
    int noCircle, noRec, noLine, noSquare = 0;
    private Map<String, Shape> shapeMap = new HashMap<>();

    public Draw() {
        initComponents();
        drawPanel = new DrawCanvas();
        jPanel2.add(drawPanel, java.awt.BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vector Drawing Application");
        setName(""); // NOI18N

        jPanel1.setName("Vector Drawing Application"); // NOI18N

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Circle");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Line Segment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setText("Square");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton4.setText("Rectangle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Shape" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Colorize");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setText("     Select Shape");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Move");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("Resize");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setText("Load");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 139, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jComboBox1.getSelectedIndex();
        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);
        if (select == null) {
            Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
            JOptionPane.showMessageDialog(null, "Please Select Shape", "Error", JOptionPane.PLAIN_MESSAGE, errorIcon);
        } else if (selectedIndex != -1) {
            
            String selectedName = (String) jComboBox1.getSelectedItem();
            
            names.remove(selectedName);
            shapeMap.remove(selectedName);
            if(shapeMap.isEmpty())
            {
                noCircle =0 ;noRec =0; noLine =0; noSquare =0;
            }
          for (Shape shape : shapeMap.values()) {
            if (!(shape instanceof Circle)) {
                noCircle=0;
                break;
             }
            else if (!(shape instanceof Rectangle)) {
                noRec=0;
                break;
             }
            else if (!(shape instanceof Square)) {
                noSquare=0;
                break;
             }
            else if (!(shape instanceof Line)) {
                noLine=0;
                break;
             }
             
            
          }
            draw.removeShape(select);
            jComboBox1.removeItemAt(selectedIndex);
            drawPanel.repaint();
        } else {
            System.out.println("No shape selected for deletion");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);

        JPanel colorPanel = new JPanel();
        if (select != null) {

            colorPanel.setLayout(new GridLayout(2, 2));
            Map<String, Color> colorMap = new HashMap<>();
            colorMap.put("Red", Color.RED);
            colorMap.put("Green", Color.GREEN);
            colorMap.put("Blue", Color.BLUE);
            colorMap.put("Yellow", Color.YELLOW);
            colorMap.put("White", Color.WHITE);
            colorMap.put("purple", Color.MAGENTA);
            colorMap.put("cyan", Color.cyan);

            JLabel fillColorLabel = new JLabel("Fill Color:");
            JButton fillColorButton = new JButton("Choose Fill Color");
            fillColorButton.setBackground(Color.WHITE);

            fillColorButton.addActionListener(e -> {

                String chosenColorName = (String) JOptionPane.showInputDialog(null, "Select Fill Color", "Fill Color", JOptionPane.PLAIN_MESSAGE, null, colorMap.keySet().toArray(), "Red");

                if (chosenColorName != null) {
                    fillColorButton.setBackground(colorMap.get(chosenColorName));
                }
            });

            JLabel outlineColorLabel = new JLabel("Outline Color:");
            JButton outlineColorButton = new JButton("Choose Outline Color");
            outlineColorButton.setBackground(Color.WHITE);

            outlineColorButton.addActionListener(e -> {
                String chosenColorName = (String) JOptionPane.showInputDialog(null, "Select Outline Color", "Outline Color", JOptionPane.PLAIN_MESSAGE, null, colorMap.keySet().toArray(), "Blue");

                if (chosenColorName != null) {
                    outlineColorButton.setBackground(colorMap.get(chosenColorName));
                }
            });

            // Add the labels and buttons to the panel
            colorPanel.add(fillColorLabel);
            colorPanel.add(fillColorButton);
            colorPanel.add(outlineColorLabel);
            colorPanel.add(outlineColorButton);

            int result = JOptionPane.showConfirmDialog(null, colorPanel, "Select Fill and Outline Colors", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {

                if (outlineColorButton.getBackground() != Color.white && fillColorButton.getBackground() != Color.white) {
                    Color fillColor = fillColorButton.getBackground();
                    Color outlineColor = outlineColorButton.getBackground();
                    select.setFillColor(fillColor);
                    select.setColor(outlineColor);
                    drawPanel.repaint();
                } else if (outlineColorButton.getBackground() != Color.white && fillColorButton.getBackground() == Color.white) {
                    Color outlineColor = outlineColorButton.getBackground();
                    select.setColor(outlineColor);
                    drawPanel.repaint();
                } else if (outlineColorButton.getBackground() == Color.white && fillColorButton.getBackground() != Color.white) {
                    Color fillColor = fillColorButton.getBackground();
                    select.setFillColor(fillColor);
                    System.out.println(select.getFillColor().toString());
                    drawPanel.repaint();
                } else {
                    Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
                    JOptionPane.showMessageDialog(null, "Please Select At least one color", "Error", JOptionPane.PLAIN_MESSAGE, errorIcon);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);
        if (select != null) {
            Map<String, Double> prop = select.getProperties();
            System.out.println(prop);
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JTextField lengthField = new JTextField(10);
        JTextField widthField = new JTextField(10);
        JTextField centerField = new JTextField(10);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("length"));
        panel.add(lengthField);
        panel.add(new JLabel("width"));
        panel.add(widthField);
        panel.add(new JLabel("center"));
        panel.add(centerField);
        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            try {
                Double length = Double.parseDouble(lengthField.getText());
                Double width = Double.parseDouble(widthField.getText());
                String[] centerValues = centerField.getText().split(",");
                int centerX = Integer.parseInt(centerValues[0].trim());
                int centerY = Integer.parseInt(centerValues[1].trim());
                Point center = new Point(centerX, centerY);
                Map<String, Double> properties = new HashMap<>();
                properties.put("length", length);
                properties.put("width", width);
                properties.put("centerX", (double) centerX);
                properties.put("centerY", (double) centerY);
                Rectangle r = new Rectangle();
                r.setProperties(properties);
                draw.addShape(r);
                drawPanel.repaint();
                noRec++;
                String name = "Rectangle " + noRec;
                names.add(name);
                jComboBox1.addItem(name);
                shapeMap.put(name, r);

            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JTextField side = new JTextField(10);
        JTextField center = new JTextField(10);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));
        panel.add(new JLabel("Side Length"));
        panel.add(side);
        panel.add(new JLabel("center"));
        panel.add(center);

        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            int centerX, centerY;
            Point position;
            try {
                String[] Values = center.getText().split(",");
                if (Values.length < 2) {

                    System.out.println("Enter 2 inputs for x and y");

                }

                centerX = Integer.parseInt(Values[0].trim());
                centerY = Integer.parseInt(Values[1].trim());
                position = new Point(centerX, centerY);
                Double sideLength = Double.parseDouble(side.getText());
                Square s = new Square();
                Map<String, Double> properties = new HashMap<>();
                properties.put("side", sideLength);
                properties.put("centerX", (double) centerX);
                properties.put("centerY", (double) centerY);
                s.setProperties(properties);
                draw.addShape(s);
                noSquare++;
                String name = "Square" + noSquare;
                names.add(name);
                drawPanel.repaint();
                jComboBox1.addItem(name);
                shapeMap.put(name, s);
            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JTextField stpointField = new JTextField(10);
        JTextField length = new JTextField(10);
        JTextField angle = new JTextField(10);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("start point"));
        panel.add(stpointField);
        panel.add(new JLabel("length"));
        panel.add(length);
        panel.add(new JLabel("angle"));
        panel.add(angle);
        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            int startX, startY;
            Point start;
            try {
                String[] Values = stpointField.getText().split(",");
                if (Values.length < 2) {
                    System.out.println("Enter 2 inputs for x and y");
                }
                startX = Integer.parseInt(Values[0].trim());
                startY = Integer.parseInt(Values[1].trim());
                start = new Point(startX, startY);
                Double len = Double.parseDouble(length.getText());
                Double ang = Double.parseDouble(angle.getText());
                Line l = new Line();
                Map<String, Double> properties = new HashMap<>();
                properties.put("length", len);
                properties.put("angle", ang);
                properties.put("centerX", (double) startX);
                properties.put("centerY", (double) startY);
                l.setProperties(properties);
                draw.addShape(l);
                drawPanel.repaint();
                noLine++;
                String name = "Line " + noLine;
                names.add(name);
                jComboBox1.addItem(name);
                shapeMap.put(name, l);
            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JTextField radiusField = new JTextField(10);
        JTextField centerField = new JTextField(10);
        JPanel panel = new JPanel();

        panel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));
        panel.add(new JLabel("radius"));
        panel.add(radiusField);
        panel.add(new JLabel("center"));
        panel.add(centerField);
        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            try {
                Double radius = Double.parseDouble(radiusField.getText());
                String[] centerValues = centerField.getText().split(",");
                int centerX = Integer.parseInt(centerValues[0].trim());
                int centerY = Integer.parseInt(centerValues[1].trim());
                Point center = new Point(centerX, centerY);
                Circle c = new Circle();
                Map<String, Double> properties = new HashMap<>();
                properties.put("radius", radius);
                properties.put("centerX", (double) centerX);
                properties.put("centerY", (double) centerY);
                c.setProperties(properties);
                draw.addShape(c);
                drawPanel.repaint();
                noCircle++;
                String name = "Circle " + noCircle;
                shapeMap.put(name, c);
                names.add(name);
                jComboBox1.addItem(name);
            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }

        }
    }

    private class DrawCanvas extends JPanel {

        public DrawCanvas() {
            setBackground(Color.WHITE);

            setSize(500, 500);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            draw.refresh(g);
           

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JButton move;
         int selectedIndex = jComboBox1.getSelectedIndex();
        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);
        if (select == null) {
            Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
            JOptionPane.showMessageDialog(null, "Please Select Shape", "Error", JOptionPane.PLAIN_MESSAGE, errorIcon);
        } else if (selectedIndex != -1) {

         String selectedName = (String) jComboBox1.getSelectedItem();
         JFrame frame = new JFrame("Move Shape ");
        JTextField newX = new JTextField(7);
        JTextField newY = new JTextField(7);
        JPanel panel = new JPanel(null);
        frame.setBounds(300, 200, 300, 200);
        panel.setBounds(300, 200, 300, 200);
        frame.setResizable(false);
        
        
        JLabel x= new JLabel("Enter New X");
        x.setBounds(20, 20, 100, 25);
        newX.setBounds(120, 20, 150, 25);
        panel.add(x);
        panel.add(newX);
        
        
        JLabel y= new JLabel("Enter New Y");
        y.setBounds(20, 60, 100, 25);
        panel.add(y);
        newY.setBounds(120, 60, 150, 25);
        panel.add(newY);
        
        move= new JButton("Move");
        move.setBounds(100, 100, 100, 40);
        move.setBackground(Color.GRAY);
        panel.add(move);
        frame.add(panel);
        
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        panel.setVisible(true);
        ActionListener e = new ActionListener (){
            
            @Override
            public void actionPerformed(ActionEvent e)
            {
                try{
                double x ;
                double y ;
                if(!newX.getText().isEmpty()&&! newY.getText().isEmpty())
                {
                     x =Double.parseDouble( newX.getText().trim());
                     y = Double.parseDouble(newY.getText().trim());
                     if(x>0 && y>0){
                    Map<String, Double> properties = new HashMap<>();
                    properties.put("centerX", x);
                    properties.put("centerY", y);
                    select.setProperties(properties);
                    drawPanel.repaint();
                    frame.dispose();   }
                     else
                         JOptionPane.showMessageDialog(null, "Please enter valid numeric x & y", "Error", JOptionPane.ERROR_MESSAGE);
}
              
            }catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(null, "Please enter valid numeric values for X and Y!", "Error", JOptionPane.ERROR_MESSAGE);
                
                }
             }
            
         
       
        
        };
        move.addActionListener(e);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:0
         int selectedIndex = jComboBox1.getSelectedIndex();
        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);
        if (select == null) {
            Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
            JOptionPane.showMessageDialog(null, "Please Select Shape", "Error", JOptionPane.PLAIN_MESSAGE, errorIcon);
        } else if (selectedIndex != -1) {
            JFrame frame = new JFrame("Resize shape ");
            frame.setBounds(300, 200, 300, 200);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            JPanel panel = new JPanel(null);
            frame.add(panel);
            panel.setVisible(true);
            panel.setBounds(300, 200, 300, 200);
            frame.setResizable(false);
            JButton resize = new JButton("Resize ");
            resize.setBounds(100, 100, 100, 40);
            resize.setBackground(Color.GRAY);
            panel.add(resize);
            
            if(select instanceof Circle)
            {
                
                 JTextField radius = new JTextField(7);
                 JLabel r = new JLabel("Enter new Radius");
                 r.setBounds(20, 20, 100, 25);
                 radius.setBounds(120, 20, 150, 25);
                 panel.add(r);
                 panel.add(radius);
              ActionListener e = new ActionListener(){
                public void actionPerformed(ActionEvent e)
                   {        
                       try{
                      double r = Double.parseDouble(radius.getText().trim());
                      if(r>0)
                      {
                      Map <String , Double> properties = new HashMap<>();
                      properties.put("radius",r );
                      select.setProperties(properties);
                      drawPanel.repaint();
                      frame.dispose();
                      }
                      else
                          JOptionPane.showMessageDialog(null, "Please enter valid numeric radius", "Error", JOptionPane.ERROR_MESSAGE);
                       }catch(NumberFormatException ex)
                       {
                           System.out.println("please ensure you enter valid new radius");
                       }
                       catch (Exception ex) {
                        System.out.println("Error in input: " + ex.getMessage());
                     }
                          
                   }
                  };resize.addActionListener(e);
              
            }
            else if(select instanceof Rectangle){
                 JTextField length  = new JTextField(7);
                 JTextField width  = new JTextField(7);
                 panel.setBounds(300, 200, 300, 200);
                 JLabel l = new JLabel("Enter new length");
                 JLabel w = new JLabel("Enter new width");
                 l.setBounds(20, 20, 100, 25);
                 w.setBounds(20, 60, 100, 25);
                 length.setBounds(120, 20, 150, 25);
                 width.setBounds(120, 60, 150, 25);
                 panel.add(l); panel.add(w);
                 panel.add(length); panel.add(width);
              ActionListener e = new ActionListener(){
                public void actionPerformed(ActionEvent e)
                   {           
                       try{
                      double new_length ;
                      double new_width ;
                      if(!length.getText().isEmpty() & !width.getText().isEmpty() )
                      {
                         new_length = Double.parseDouble(length.getText().trim());
                         new_width= Double.parseDouble(width.getText().trim());
                         if(new_length>0 & new_width>0)
                        {
                      Map <String , Double> properties = new HashMap<>();
                      properties.put("length",new_length );
                      properties.put("width",new_width );
                      select.setProperties(properties);
                      drawPanel.repaint();
                      frame.dispose();
                        }
                      else 
                        JOptionPane.showMessageDialog(null, "Please enter valid numeric length & width", "Error", JOptionPane.ERROR_MESSAGE);
                        
                      }
                    else if (width.getText().isEmpty()& !length.getText().isEmpty()) {
                               Map<String, Double> properties = new HashMap<>();
                               new_length = Double.parseDouble(length.getText().trim());
                               if(new_length>0){
                               properties.put("length", new_length);
                               select.setProperties(properties);
                               drawPanel.repaint();
                               frame.dispose();
                               }else
                                  JOptionPane.showMessageDialog(null, "Please enter valid numeric length ", "Error", JOptionPane.ERROR_MESSAGE);
                           }
                    else if(!width.getText().isEmpty()& length.getText().isEmpty())
                    {
                         Map<String, Double> properties = new HashMap<>();
                               new_width = Double.parseDouble(width.getText().trim());
                               if(new_width>0){
                               properties.put("width", new_width);
                               select.setProperties(properties);
                               drawPanel.repaint();
                               frame.dispose();
                               }else
                                  JOptionPane.showMessageDialog(null, "Please enter valid numeric width", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                       }catch(NumberFormatException ex )
                       {
                         System.out.println("Error: Please ensure the input contains valid new side lenght");
                       }
                      catch (Exception ex) {
                        System.out.println("Error in input: " + ex.getMessage());
                     }
                   }
                  };resize.addActionListener(e);
              
            
            }
            else if(select instanceof Square)
            {
                 JTextField side = new JTextField(7);
                 JLabel s = new JLabel("Enter new side");
                 s.setBounds(20, 20, 100, 25);
                 side.setBounds(120, 20, 150, 25);
                 panel.add(s);
                 panel.add(side);
              ActionListener e = new ActionListener(){
                public void actionPerformed(ActionEvent e)
                   {         
                      try{
                       double new_side = Double.parseDouble(side.getText().trim());
                      
                      if(new_side >0)
                      {
                      Map <String , Double> properties = new HashMap<>();
                      properties.put("side",new_side );
                      select.setProperties(properties);
                      drawPanel.repaint();
                      frame.dispose();
                      }
                      else
                          JOptionPane.showMessageDialog(null, "Please enter valid numeric radius", "Error", JOptionPane.ERROR_MESSAGE);
                      }catch (NumberFormatException ex) {

                   System.out.println("Error: Please ensure the input contains valid new side lenght");
                     } catch (Exception ex) {
                        System.out.println("Error in input: " + ex.getMessage());
                     }
                          
                          
                   }
                  };resize.addActionListener(e);
            }
            else if(select instanceof Line)
            {
                JTextField length = new JTextField(7);
                JTextField angle = new JTextField(7);
                 JLabel l = new JLabel("Enter new length");
                 JLabel a = new JLabel("Enter new angle");
                 l.setBounds(20, 20, 100, 25);
                 a.setBounds(20, 60, 100, 25);
                 length.setBounds(120, 20, 150, 25);
                 angle.setBounds(120, 60, 150, 25);
                 panel.add(l);panel.add(a);
                 panel.add(length); panel.add(angle);
              ActionListener e = new ActionListener(){
                public void actionPerformed(ActionEvent e)
                   {         
                      try{
                      double new_length ,new_angle;
                      if(!length.getText().isEmpty()& !angle.getText().isEmpty())
                      {
                       new_length = Double.parseDouble(length.getText().trim());
                       new_angle =Double.parseDouble(angle.getText().trim());
                      if(new_length>0 & new_angle>=0){
                      Map <String , Double> properties = new HashMap<>();
                      properties.put("length",new_length );
                      properties.put("angle", new_angle);
                      select.setProperties(properties);
                      drawPanel.repaint();
                      frame.dispose();
                      }
                      else
                        JOptionPane.showMessageDialog(null, "Please enter valid numeric ", "Error", JOptionPane.ERROR_MESSAGE);
                          
                      }
                          else if (!angle.getText().isEmpty() & length.getText().isEmpty()) {
                             
                              new_angle = Double.parseDouble(angle.getText().trim());
                              if(new_angle>=0){
                              Map<String, Double> properties = new HashMap<>();
                              properties.put("angle", new_angle);
                              select.setProperties(properties);
                              drawPanel.repaint();
                              frame.dispose();
                          }else
                            JOptionPane.showMessageDialog(null, "Please enter valid numeric ", "Error", JOptionPane.ERROR_MESSAGE);
                          }
                           else if (angle.getText().isEmpty() & !length.getText().isEmpty()) {
                             
                              new_length= Double.parseDouble(length.getText().trim());
                              if(new_length>0){
                              Map<String, Double> properties = new HashMap<>();
                              properties.put("length", new_length);
                              select.setProperties(properties);
                              drawPanel.repaint();
                              frame.dispose();
                          }else
                            JOptionPane.showMessageDialog(null, "Please enter valid numeric ", "Error", JOptionPane.ERROR_MESSAGE);
                           }
                      
                      }catch (NumberFormatException ex) {

                   System.out.println("Error: Please ensure the input contains valid new length and angle");
                     } catch (Exception ex) {
                        System.out.println("Error in input: " + ex.getMessage());
                     }
                          
                          
                   }
                  };resize.addActionListener(e);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 
            JFrame frame =new JFrame("save");
            JFileChooser fc = new JFileChooser();
            int result = fc.showSaveDialog(null);
             fc.setDialogTitle("Save File");
            fc.setApproveButtonText("Save");
             if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fc.getSelectedFile();
                JOptionPane.showMessageDialog(frame, "Selected file: " + selectedFile.getAbsolutePath());
              try(BufferedWriter writer = new BufferedWriter(new FileWriter(selectedFile)))
               {
                    for(Map.Entry <String ,Shape> p : shapeMap.entrySet())
                    {
                        
                        String line =p.getKey();
                        Shape s = p.getValue();
                        writer.write(line);
                        writer.write(s.getProperties().toString() );
                        writer.write(s.getColor().toString() );
                        if(s.getFillColor()!=null){
                        writer.write( "," + s.getFillColor().toString());}
//                        else if(s.getFillColor()==null)
//                        {
//                            writer.write( "," + Color.WHITE.toString());
//                        }
                        writer.newLine();  
                        
                    }
                    writer.flush();
                }catch(IOException e)
                {
                    System.out.println("error");
                }
            } 
             else
                 System.out.println("no selected file");
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         JFrame frame =new JFrame("save");
            JFileChooser fc = new JFileChooser();
            int result = fc.showOpenDialog(null);
             if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fc.getSelectedFile();
                JOptionPane.showMessageDialog(frame, "Selected file: " + selectedFile.getAbsolutePath());
        try(BufferedReader reader = new BufferedReader(new FileReader(selectedFile)))
        {
            
            String line ;
            while((line= reader.readLine())!=null)
            {
                if(line.startsWith("Square"))
                {
                   String properties = line.substring(line.indexOf("{") + 1, line.indexOf("}"));
                   Map<String, Double> propertyMap = new HashMap<>();
                  String[] keyValuePairs = properties.split(", ");

        for (String pair : keyValuePairs) {
            String[] keyValue = pair.split("=");
            if (keyValue.length == 2) {
                propertyMap.put(keyValue[0].trim(), Double.parseDouble(keyValue[1].trim()));
            }
        }    
                Square square = new Square();
                  String s = line.substring(line.indexOf("}") + 1);

                    Pattern colorPattern = Pattern.compile("java\\.awt\\.Color\\[r=(\\d+),g=(\\d+),b=(\\d+)\\]");

                    Matcher matcher = colorPattern.matcher(s);

                    Color outlineColor = null;
                    Color fillColor = null;

                    if (matcher.find()) {

                        outlineColor = new Color(Integer.parseInt(matcher.group(1)),
                                Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }

                    if (matcher.find()) {

                        fillColor = new Color(Integer.parseInt(matcher.group(1)),
                               Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }
                    if (outlineColor != null) {
                        square.setColor(outlineColor);
                    }
                    if (fillColor != null) {
                        square.setFillColor(fillColor);
                    }

              jComboBox1.addItem(line.substring(0, line.indexOf("{")));
                square.setProperties(propertyMap);
                    draw.addShape(square);
                    drawPanel.repaint();
                     shapeMap.put(line.substring(0, line.indexOf("{")), square);
                     noSquare ++;
                }
                else if(line.startsWith("Line"))
                {
                    String properties = line.substring(line.indexOf("{") + 1, line.indexOf("}"));
                     Map<String, Double> propertyMap = new HashMap<>();
                  String[] keyValuePairs = properties.split(", ");

               for (String pair : keyValuePairs) {
            String[] keyValue = pair.split("=");
            if (keyValue.length == 2) {
                propertyMap.put(keyValue[0].trim(), Double.parseDouble(keyValue[1].trim()));
                }
                }
                  Line l = new Line();
                  noLine++;
          String s = line.substring(line.indexOf("}") + 1);

                    Pattern colorPattern = Pattern.compile("java\\.awt\\.Color\\[r=(\\d+),g=(\\d+),b=(\\d+)\\]");

                    Matcher matcher = colorPattern.matcher(s);

                    Color outlineColor = null;
                    Color fillColor = null;

                    if (matcher.find()) {

                         outlineColor = new Color(Integer.parseInt(matcher.group(1)),
                                 Integer.parseInt(matcher.group(2)),
                                 Integer.parseInt(matcher.group(3)));
                    }

                    if (matcher.find()) {

                        fillColor = new Color(Integer.parseInt(matcher.group(1)),
                               Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }
                    if (outlineColor != null) {
                        l.setColor(outlineColor);
                    }
                    if (fillColor != null) {
                        l.setFillColor(fillColor);
                    }
                    l.setProperties(propertyMap);
                    draw.addShape(l);
                     jComboBox1.addItem(line.substring(0, line.indexOf("{")));
                    drawPanel.repaint();
                    shapeMap.put(line.substring(0, line.indexOf("{")), l);
            }
                
         
                else if(line.startsWith("Rectangle"))
                {
                     String properties = line.substring(line.indexOf("{") + 1, line.indexOf("}"));
                     Map<String, Double> propertyMap = new HashMap<>();
                  String[] keyValuePairs = properties.split(", ");

               for (String pair : keyValuePairs) {
            String[] keyValue = pair.split("=");
            if (keyValue.length == 2) {
                propertyMap.put(keyValue[0].trim(), Double.parseDouble(keyValue[1].trim()));
                }
                }
                    Rectangle rec = new Rectangle();
                    noRec++;
                    String s = line.substring(line.indexOf("}") + 1);

                    Pattern colorPattern = Pattern.compile("java\\.awt\\.Color\\[r=(\\d+),g=(\\d+),b=(\\d+)\\]");

                    Matcher matcher = colorPattern.matcher(s);

                    Color outlineColor = null;
                    Color fillColor = null;

                    if (matcher.find()) {

                        outlineColor = new Color(Integer.parseInt(matcher.group(1)),
                                Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }

                    if (matcher.find()) {

                        fillColor = new Color(Integer.parseInt(matcher.group(1)),
                               Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }
                    if (outlineColor != null) {
                        rec.setColor(outlineColor);
                    }
                    if (fillColor != null) {
                        rec.setFillColor(fillColor);
                    }
                    rec.setProperties(propertyMap);
                    draw.addShape(rec);
                    jComboBox1.addItem(line.substring(0, line.indexOf("{")));
                    drawPanel.repaint();
                     shapeMap.put(line.substring(0, line.indexOf("{")), rec);
                }
                
                
                  else if(line.startsWith("Circle"))
                {
                     String properties = line.substring(line.indexOf("{") + 1, line.indexOf("}"));
                     Map<String, Double> propertyMap = new HashMap<>();
                  String[] keyValuePairs = properties.split(", ");

               for (String pair : keyValuePairs) {
            String[] keyValue = pair.split("=");
            if (keyValue.length == 2) {
                propertyMap.put(keyValue[0].trim(), Double.parseDouble(keyValue[1].trim()));
                }
                }
                  Circle c = new Circle();
                  noCircle++;
                 String s = line.substring(line.indexOf("}") + 1);

                    Pattern colorPattern = Pattern.compile("java\\.awt\\.Color\\[r=(\\d+),g=(\\d+),b=(\\d+)\\]");

                    Matcher matcher = colorPattern.matcher(s);

                    Color outlineColor = null;
                    Color fillColor = null;

                    if (matcher.find()) {

                        outlineColor = new Color(Integer.parseInt(matcher.group(1)),
                                Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }

                    if (matcher.find()) {

                        fillColor = new Color(Integer.parseInt(matcher.group(1)),
                               Integer.parseInt(matcher.group(2)),
                                Integer.parseInt(matcher.group(3)));
                    }
                    if (outlineColor != null) {
                        c.setColor(outlineColor);
                    }
                    if (fillColor != null) {
                        c.setFillColor(fillColor);
                    }


             c.setProperties(propertyMap);
                    draw.addShape(c);
                    jComboBox1.addItem(line.substring(0, line.indexOf("{")));
                    drawPanel.repaint();
                    shapeMap.put(line.substring(0, line.indexOf("{")), c);
                   
                }
}}       
        
        catch(IOException e)
                {
                    System.out.println("error");
                }}
             else
                 System.out.println("no selected file");
                 
    }//GEN-LAST:event_jButton10ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
