/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipaint;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.List;
import java.awt.Point;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import minipaint.Shape;

/**
 *
 * @author alaae
 */
public class Draw extends javax.swing.JFrame {

    /**
     * Creates new form Draw
     */
    private DrawCanvas drawPanel;
    Drawing draw = new Drawing();
    ArrayList<String> names = new ArrayList<>();
    int noCircle, noRec, noLine, noSquare = 0;
    private Map<String, Shape> shapeMap = new HashMap<>();

    public Draw() {
        initComponents();
        drawPanel = new DrawCanvas();
        jPanel2.add(drawPanel, java.awt.BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Circle");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Line Segment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Square");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Rectangle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chose Shape" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Colorize");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextField1.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1.setText("Select Shape");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(75, 191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jComboBox1.getSelectedIndex();
        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);
        if (select == null) {
            Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
            JOptionPane.showMessageDialog(null, "Please Select Shape", "Error", JOptionPane.PLAIN_MESSAGE, errorIcon);
        } else if (selectedIndex != -1) {

            String selectedName = (String) jComboBox1.getSelectedItem();
            names.remove(selectedName);
            shapeMap.remove(selectedName);
            draw.removeShape(select);
            jComboBox1.removeItemAt(selectedIndex);
            drawPanel.repaint();
        } else {
            System.out.println("No shape selected for deletion");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);

        JPanel colorPanel = new JPanel();
        if (select != null) {

            colorPanel.setLayout(new GridLayout(2, 2));
            Map<String, Color> colorMap = new HashMap<>();
            colorMap.put("Red", Color.RED);
            colorMap.put("Green", Color.GREEN);
            colorMap.put("Blue", Color.BLUE);
            colorMap.put("Yellow", Color.YELLOW);

            JLabel fillColorLabel = new JLabel("Fill Color:");
            JButton fillColorButton = new JButton("Choose Fill Color");
            fillColorButton.setBackground(Color.WHITE);

            fillColorButton.addActionListener(e -> {

                String chosenColorName = (String) JOptionPane.showInputDialog(null, "Select Fill Color", "Fill Color", JOptionPane.PLAIN_MESSAGE, null, colorMap.keySet().toArray(), "Red");

                if (chosenColorName != null) {
                    fillColorButton.setBackground(colorMap.get(chosenColorName));
                }
            });

            JLabel outlineColorLabel = new JLabel("Outline Color:");
            JButton outlineColorButton = new JButton("Choose Outline Color");
            outlineColorButton.setBackground(Color.WHITE);

            outlineColorButton.addActionListener(e -> {
                String chosenColorName = (String) JOptionPane.showInputDialog(null, "Select Outline Color", "Outline Color", JOptionPane.PLAIN_MESSAGE, null, colorMap.keySet().toArray(), "Blue");

                if (chosenColorName != null) {
                    outlineColorButton.setBackground(colorMap.get(chosenColorName));
                }
            });

            // Add the labels and buttons to the panel
            colorPanel.add(fillColorLabel);
            colorPanel.add(fillColorButton);
            colorPanel.add(outlineColorLabel);
            colorPanel.add(outlineColorButton);

            int result = JOptionPane.showConfirmDialog(null, colorPanel, "Select Fill and Outline Colors", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {

                if (outlineColorButton.getBackground() != Color.white && fillColorButton.getBackground() != Color.white) {
                    Color fillColor = fillColorButton.getBackground();
                    Color outlineColor = outlineColorButton.getBackground();
                    select.setFillColor(fillColor);
                    select.setColor(outlineColor);
                    drawPanel.repaint();
                } else if (outlineColorButton.getBackground() != Color.white && fillColorButton.getBackground() == Color.white) {
                    Color outlineColor = outlineColorButton.getBackground();
                    select.setColor(outlineColor);
                    drawPanel.repaint();
                } else if (outlineColorButton.getBackground() == Color.white && fillColorButton.getBackground() != Color.white) {
                    Color fillColor = fillColorButton.getBackground();
                    select.setFillColor(fillColor);
                    drawPanel.repaint();
                } else {
                    Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
                    JOptionPane.showMessageDialog(null, "Please Select At least one color", "Error", JOptionPane.PLAIN_MESSAGE, errorIcon);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBox1.getSelectedItem();
        Shape select = shapeMap.get(selected);
        if (select != null) {
            Map<String, Double> prop = select.getProperties();
            System.out.println(prop);
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JTextField lengthField = new JTextField(10);
        JTextField widthField = new JTextField(10);
        JTextField centerField = new JTextField(10);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("length"));
        panel.add(lengthField);
        panel.add(new JLabel("width"));
        panel.add(widthField);
        panel.add(new JLabel("center"));
        panel.add(centerField);
        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            try {
                Double length = Double.parseDouble(lengthField.getText());
                Double width = Double.parseDouble(widthField.getText());
                String[] centerValues = centerField.getText().split(",");
                int centerX = Integer.parseInt(centerValues[0].trim());
                int centerY = Integer.parseInt(centerValues[1].trim());
                Point center = new Point(centerX, centerY);
                Map<String, Double> properties = new HashMap<>();
                properties.put("length", length);
                properties.put("width", width);
                properties.put("centerX", (double) centerX);
                properties.put("centerY", (double) centerY);
                Rectangle r = new Rectangle();
                r.setProperties(properties);
                draw.addShape(r);
                drawPanel.repaint();
                noRec++;
                String name = "Rectangle " + noRec;
                names.add(name);
                jComboBox1.addItem(name);
                shapeMap.put(name, r);

            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JTextField side = new JTextField(10);
        JTextField center = new JTextField(10);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));
        panel.add(new JLabel("Side Length"));
        panel.add(side);
        panel.add(new JLabel("center"));
        panel.add(center);

        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            int centerX, centerY;
            Point postion;
            try {
                String[] Values = center.getText().split(",");
                if (Values.length < 2) {

                    System.out.println("Enter 2 inputs for x and y");

                }

                centerX = Integer.parseInt(Values[0].trim());
                centerY = Integer.parseInt(Values[1].trim());
                postion = new Point(centerX, centerY);
                Double sideLength = Double.parseDouble(side.getText());
                Square s = new Square();
                Map<String, Double> properties = new HashMap<>();
                properties.put("side", sideLength);
                properties.put("centerX", (double) centerX);
                properties.put("centerY", (double) centerY);
                s.setProperties(properties);
                draw.addShape(s);
                noSquare++;
                String name = "Square" + noSquare;
                names.add(name);
                drawPanel.repaint();
                jComboBox1.addItem(name);
                shapeMap.put(name, s);
            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JTextField stpointField = new JTextField(10);
        JTextField length = new JTextField(10);
        JTextField angle = new JTextField(10);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("start point"));
        panel.add(stpointField);
        panel.add(new JLabel("length"));
        panel.add(length);
        panel.add(new JLabel("angle"));
        panel.add(angle);
        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            int startX, startY;
            Point start;
            try {
                String[] Values = stpointField.getText().split(",");
                if (Values.length < 2) {
                    System.out.println("Enter 2 inputs for x and y");
                }
                startX = Integer.parseInt(Values[0].trim());
                startY = Integer.parseInt(Values[1].trim());
                start = new Point(startX, startY);
                Double len = Double.parseDouble(length.getText());
                Double ang = Double.parseDouble(angle.getText());
                Line l = new Line();
                Map<String, Double> properties = new HashMap<>();
                properties.put("length", len);
                properties.put("angle", ang);
                properties.put("startX", (double) startX);
                properties.put("startY", (double) startY);
                l.setProperties(properties);
                draw.addShape(l);
                drawPanel.repaint();
                noLine++;
                String name = "Line " + noLine;
                names.add(name);
                jComboBox1.addItem(name);
                shapeMap.put(name, l);
            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JTextField radiusField = new JTextField(10);
        JTextField centerField = new JTextField(10);
        JPanel panel = new JPanel();

        panel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));
        panel.add(new JLabel("raduis"));
        panel.add(radiusField);
        panel.add(new JLabel("center"));
        panel.add(centerField);
        int x = JOptionPane.showConfirmDialog(this, panel, "Enter Details", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.OK_OPTION) {
            try {
                Double radius = Double.parseDouble(radiusField.getText());
                String[] centerValues = centerField.getText().split(",");
                int centerX = Integer.parseInt(centerValues[0].trim());
                int centerY = Integer.parseInt(centerValues[1].trim());
                Point center = new Point(centerX, centerY);
                Circle c = new Circle();
                Map<String, Double> properties = new HashMap<>();
                properties.put("raduis", radius);
                properties.put("centerX", (double) centerX);
                properties.put("centerY", (double) centerY);
                c.setProperties(properties);
                draw.addShape(c);
                drawPanel.repaint();
                noCircle++;
                String name = "Circle " + noCircle;
                shapeMap.put(name, c);
                names.add(name);
                jComboBox1.addItem(name);
            } catch (NumberFormatException e) {

                System.out.println("Error: Please ensure the input contains valid numbers for X and Y.");
            } catch (Exception e) {
                System.out.println("Error in input: " + e.getMessage());
            }

        }
    }

    private class DrawCanvas extends JPanel {

        public DrawCanvas() {
            setBackground(Color.WHITE);
            setSize(250, 250);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            draw.refresh(g);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
